In [1]:
# gather_keys_oauth2.py로 키 값 가져 올것
import fitbit
import json
%matplotlib inline
from pandas import Series, DataFrame
import pandas as pd
import operator
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import copy
import math
import json
import datetime
from pandas.io.json import json_normalize
matplotlib.rc('font',family='AppleGothic')
clientID = '227L4P'
clientSecret = 'bdd25aad162c4bd752d3d5ab330bc210'
accessToken = 'eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0NjE4MjM4OTQsInNjb3BlcyI6InJ3ZWkgcnBybyByaHIgcmxvYyBybnV0IHJzbGUgcnNldCByc29jIHJhY3QiLCJzdWIiOiI0RkcyNUIiLCJhdWQiOiIyMjdMNFAiLCJpc3MiOiJGaXRiaXQiLCJ0eXAiOiJhY2Nlc3NfdG9rZW4iLCJpYXQiOjE0NjE4MjAyOTR9.u-mqWLUpr6a5E1ptKlSxEZq8cwq73kd0uTZ-QAOzQ48'
refreshToken = '17b6f7cc5f56cdf5f21a26b3647790edaf977e9efb4463643f0bfaab60b67d34'

In [2]:
authd_client = fitbit.Fitbit('227L4P', 'bdd25aad162c4bd752d3d5ab330bc210',
                            access_token = accessToken, refresh_token = refreshToken)

In [3]:
intra_sleep = authd_client.sleep(date = '2016-04-27')
SleepDF = json_normalize(intra_sleep[u'sleep'][0][u'minuteData'])

In [4]:
intradayS = authd_client.intraday_time_series('activities/steps', base_date = '2016-04-23', detail_level = '1min', start_time= None, end_time= None)
StepDF = json_normalize(intradayS[u'activities-steps-intraday'][u'dataset'])

In [5]:
intradayH = authd_client.intraday_time_series('activities/heart', base_date = '2016-04-23', detail_level = '1min', start_time= None, end_time= None)
HeartDF = json_normalize(intradayH[u'activities-heart-intraday'][u'dataset'])

In [6]:
SleepDF

     dateTime value
0    03:05:30     3
1    03:06:30     3
2    03:07:30     1
3    03:08:30     2
4    03:09:30     2
5    03:10:30     2
6    03:11:30     2
7    03:12:30     1
8    03:13:30     1
9    03:14:30     1
10   03:15:30     1
11   03:16:30     1
12   03:17:30     1
13   03:18:30     1
14   03:19:30     1
15   03:20:30     1
16   03:21:30     1
17   03:22:30     1
18   03:23:30     1
19   03:24:30     1
20   03:25:30     1
21   03:26:30     1
22   03:27:30     1
23   03:28:30     1
24   03:29:30     1
25   03:30:30     1
26   03:31:30     1
27   03:32:30     2
28   03:33:30     2
29   03:34:30     1
..        ...   ...
255  07:20:30     1
256  07:21:30     1
257  07:22:30     1
258  07:23:30     1
259  07:24:30     2
260  07:25:30     1
261  07:26:30     1
262  07:27:30     1
263  07:28:30     1
264  07:29:30     1
265  07:30:30     1
266  07:31:30     1
267  07:32:30     1
268  07:33:30     2
269  07:34:30     2
270  07:35:30     2
271  07:36:30     1
272  07:37:30     1
273  07:38:30     1
274  07:39:30     2
275  07:40:30     1
276  07:41:30     1
277  07:42:30     1
278  07:43:30     1
279  07:44:30     1
280  07:45:30     1
281  07:46:30     1
282  07:47:30     2
283  07:48:30     1
284  07:49:30     2

[285 rows x 2 columns]